"use client"

import { useMemo, useState } from "react"
import { Activity, ArrowLeft, Check, ChevronDown, Clipboard, Clock3, Copy, KeyRound, Menu, Moon, Search, Send, Sun, X, Zap } from "lucide-react"
import { categories, endpoints, type ApiCategory, type Endpoint } from "@/lib/api-data"

const methodStyles: Record<string, string> = { GET: "text-primary bg-primary/10 border-primary/20", POST: "text-success bg-success/10 border-success/20", PUT: "text-warning bg-warning/10 border-warning/20", DELETE: "text-danger bg-danger/10 border-danger/20" }

function MethodBadge({ method }: { method: string }) { return <span className={`code rounded-md border px-2 py-1 text-[10px] font-bold tracking-wider ${methodStyles[method]}`}>{method}</span> }
function CopyButton({ value, label = "Copy" }: { value: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  const copy = async () => { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <button onClick={copy} className="inline-flex min-h-9 items-center gap-2 rounded-md border border-border px-3 text-xs text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground" aria-label={`${label} to clipboard`}>{copied ? <Check size={13} className="text-success" /> : <Copy size={13} />}{copied ? "Copied" : label}</button>
}
function CodeBlock({ children, copy }: { children: string; copy?: boolean }) { return <div className="relative overflow-hidden rounded-lg border border-border bg-[#0b0e13]"><pre className="code overflow-x-auto p-4 text-[11px] leading-6 text-[#aab7c9]">{children}</pre>{copy && <div className="absolute right-2 top-2"><CopyButton value={children} label="" /></div>}</div> }
function EndpointCard({ endpoint, expanded, onToggle, onToast }: { endpoint: Endpoint; expanded: boolean; onToggle: () => void; onToast: (text: string) => void }) {
  const [testing, setTesting] = useState(false); const [sent, setSent] = useState(false); const [requestValue, setRequestValue] = useState(endpoint.params[0]?.example ?? ""); const [responseStatus, setResponseStatus] = useState<number | null>(null); const [responseBody, setResponseBody] = useState(""); const [responseError, setResponseError] = useState("")
  const run = async () => {
    setTesting(true); setSent(false); setResponseStatus(null); setResponseBody(""); setResponseError("")
    const params = new URLSearchParams({ [endpoint.params[0]?.name ?? "url"]: requestValue })
    try {
      const response = await fetch(`${endpoint.path}?${params.toString()}`, { headers: { Accept: "application/json" } })
      const text = await response.text()
      if (!response.ok) throw new Error(`HTTP ${response.status}${text ? `: ${text.slice(0, 140)}` : ""}`)
      setResponseStatus(response.status); setResponseBody(text); setSent(true)
    } catch (error) {
      setResponseError(error instanceof Error ? error.message : "Request failed")
    } finally { setTesting(false) }
  }
  return <article className={`overflow-hidden rounded-xl border bg-card/80 transition-colors ${expanded ? "border-primary/45" : "border-border hover:border-[#3b4658]"}`}>
    <button onClick={onToggle} className="flex w-full items-center gap-3 p-4 text-left sm:p-5" aria-expanded={expanded}>
      <MethodBadge method={endpoint.method} /><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium text-foreground">{endpoint.name}</div><div className="code mt-1 truncate text-[11px] text-muted-foreground">{endpoint.path}</div></div><ChevronDown size={17} className={`shrink-0 text-muted-foreground transition-transform ${expanded ? "rotate-180 text-primary" : ""}`} />
    </button>
    {expanded && <div className="animate-in border-t border-border px-4 pb-5 pt-4 sm:px-5">
      <p className="mb-5 max-w-2xl text-sm leading-6 text-muted-foreground">{endpoint.description}</p>
      <div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]">
        <div><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.18em] text-muted-foreground">REQUEST</span><CopyButton value={endpoint.path} label="Copy URL" /></div><div className="code rounded-lg border border-border bg-muted/50 p-3 text-xs text-primary">{endpoint.method} {endpoint.path}</div><div className="mt-5 mb-3 text-[10px] font-bold tracking-[0.18em] text-muted-foreground">PARAMETERS</div><div className="divide-y divide-border rounded-lg border border-border">{endpoint.params.map(param => <div key={param.name} className="flex flex-wrap items-center gap-x-3 gap-y-1 px-3 py-3 text-xs"><span className="code text-foreground">{param.name}</span><span className="rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">{param.type}</span>{param.required && <span className="text-[10px] text-danger">required</span>}<span className="basis-full truncate text-[11px] text-muted-foreground">e.g. {param.example}</span></div>)}</div></div>
        <div><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.18em] text-muted-foreground">EXAMPLE RESPONSE</span><CopyButton value={endpoint.example} label="Copy" /></div><CodeBlock copy>{endpoint.example}</CodeBlock><button onClick={() => { setTesting(true); onToast("Tester opened below") }} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-md bg-primary px-4 text-xs font-semibold text-primary-foreground transition-colors hover:bg-primary/85"><Zap size={14} /> Try endpoint</button></div>
      </div>
      {testing && <div className="animate-in mt-6 border-t border-border pt-5"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.18em] text-muted-foreground">API TESTER</span><button onClick={() => setTesting(false)} aria-label="Close tester"><X size={16} className="text-muted-foreground" /></button></div><div className="flex flex-col gap-2 sm:flex-row"><div className="code flex min-h-10 items-center rounded-md border border-border bg-muted/40 px-3 text-xs text-primary">{endpoint.method} {endpoint.path}</div><input value={requestValue} onChange={event => setRequestValue(event.target.value)} className="min-h-10 min-w-0 flex-1 rounded-md border border-border bg-[#0b0e13] px-3 text-xs text-foreground outline-none placeholder:text-muted-foreground focus:border-primary" placeholder={endpoint.params[0]?.example ?? "Enter a value"} /></div><button onClick={run} disabled={testing} className="mt-3 inline-flex min-h-10 items-center gap-2 rounded-md border border-primary/40 bg-primary/10 px-4 text-xs font-semibold text-primary hover:bg-primary/20 disabled:opacity-70">{testing ? <><Activity size={14} className="spin" /> Sending request...</> : <><Send size={14} /> Send request</>}</button>{responseError && <div role="alert" className="mt-4 rounded-lg border border-danger/30 bg-danger/10 p-3 text-xs text-danger"><div className="font-semibold">Request failed</div><div className="mt-1 break-words opacity-90">{responseError}</div></div>}{sent && <div className="mt-4"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.18em] text-muted-foreground">RESPONSE <span className="ml-2 text-success">{responseStatus ?? 200} OK</span></span><CopyButton value={endpoint.example} label="Copy response" /></div><CodeBlock>{responseBody || endpoint.example}</CodeBlock></div>}</div>}
    </div>}
  </article>
}
function Stat({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="min-w-0 rounded-lg border border-border bg-card/60 p-3"><div className="text-[9px] font-bold tracking-[0.16em] text-muted-foreground">{label}</div><div className="mt-1 flex items-baseline gap-2"><span className="text-base font-semibold">{value}</span>{detail && <span className="text-[10px] text-success">{detail}</span>}</div></div> }
function KeyCard({ onToast }: { onToast: (text: string) => void }) { return <aside className="rounded-xl border border-border bg-card/70 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-semibold"><KeyRound size={14} className="text-primary" /> API KEY</div><span className="rounded-full bg-success/10 px-2 py-1 text-[9px] font-bold tracking-wider text-success">PRO</span></div><div className="code mt-4 rounded-md border border-border bg-muted/40 px-3 py-2.5 text-xs text-muted-foreground">bmw_pro_47f8••••••••</div><button onClick={() => onToast("API key copied") } className="mt-3 flex items-center gap-2 text-[11px] text-primary hover:underline"><Clipboard size={13} /> Copy key</button><div className="mt-5 flex items-end justify-between"><div><div className="text-[10px] text-muted-foreground">Requests today</div><div className="mt-1 text-sm font-medium">1,284 <span className="text-xs text-muted-foreground">/ 5,000</span></div></div><span className="text-xs text-muted-foreground">25.6%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full w-[26%] rounded-full bg-primary" /></div><div className="mt-4 flex justify-between border-t border-border pt-3 text-[11px]"><span className="text-muted-foreground">Remaining</span><span className="font-medium">3,716</span></div></aside> }

export default function Home() {
  const [category, setCategory] = useState<ApiCategory>("All"); const [query, setQuery] = useState(""); const [open, setOpen] = useState("youtube"); const [dark, setDark] = useState(true); const [toast, setToast] = useState("")
  const filtered = useMemo(() => endpoints.filter(e => (category === "All" || e.category === category) && `${e.name} ${e.path} ${e.description}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const showToast = (text: string) => { setToast(text); window.setTimeout(() => setToast(""), 1800) }
  return <div className={`${dark ? "" : "light"} grid-bg min-h-screen`}><header className="sticky top-0 z-20 border-b border-border/80 bg-[#090b0fee] backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1320px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-7"><div className="text-base font-semibold tracking-tight"><span>BMW</span> <span className="text-primary">APIs</span></div><div className="hidden items-center gap-2 border-l border-border pl-7 text-[11px] text-muted-foreground md:flex"><span className="h-1.5 w-1.5 rounded-full bg-success shadow-[0_0_8px_#42d392]" /> API online <span className="text-border">/</span> <Clock3 size={12} /> 01:13:12</div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 text-[11px] text-success sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-success" /> operational</div><button onClick={() => setDark(!dark)} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Toggle theme">{dark ? <Sun size={16} /> : <Moon size={16} />}</button><button className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Open menu"><Menu size={17} /></button></div></div></header>
    <main className="mx-auto max-w-[1320px] px-4 py-8 sm:px-6 sm:py-10 lg:px-8"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><button className="mb-5 inline-flex items-center gap-2 text-[10px] font-bold tracking-[0.16em] text-muted-foreground transition-colors hover:text-primary"><ArrowLeft size={13} /> BACK <span className="text-border">//</span> RE-BOOT</button><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">API PLAYGROUND</h1><p className="mt-2 text-sm text-muted-foreground">Explore and test available endpoints</p></div><div className="w-full sm:max-w-[235px]"><KeyCard onToast={showToast} /></div></div><div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="API STATUS" value="ONLINE" detail="100%" /><Stat label="TOTAL ENDPOINTS" value="24" /><Stat label="REQUESTS TODAY" value="1,284" detail="+12.4%" /><Stat label="UPTIME" value="99.9%" detail="30d" /></div><div className="mb-5 overflow-hidden rounded-xl border border-border bg-card/45"><div className="flex gap-1 overflow-x-auto p-1.5">{categories.map(item => <button key={item.label} onClick={() => setCategory(item.label)} className={`shrink-0 rounded-md px-3 py-2 text-xs transition-colors ${category === item.label ? "bg-primary/15 text-primary" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{item.label}{item.count && <span className="ml-1.5 text-[10px] opacity-60">{item.count}</span>}</button>)}</div></div><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search endpoints..." className="h-11 w-full rounded-lg border border-border bg-card/70 pl-10 pr-4 text-sm outline-none placeholder:text-muted-foreground focus:border-primary/60" /></div><div className="text-[11px] text-muted-foreground">{filtered.length} endpoint{filtered.length === 1 ? "" : "s"} available</div></div><div className="space-y-2.5">{filtered.map(endpoint => <EndpointCard key={endpoint.id} endpoint={endpoint} expanded={open === endpoint.id} onToggle={() => setOpen(open === endpoint.id ? "" : endpoint.id)} onToast={showToast} />)}{!filtered.length && <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No endpoints match your search.</div>}</div><div className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card/50 p-5"><div className="mb-4 flex items-center gap-2 text-xs font-semibold"><Zap size={15} className="text-warning" /> Quick start</div><p className="max-w-lg text-sm leading-6 text-muted-foreground">Use your API key in the <span className="code text-xs text-primary">Authorization</span> header to authenticate requests.</p><CodeBlock>curl https://api.bmwapis.dev/v1/health \\
  -H &quot;Authorization: Bearer bmw_pro_47f8...&quot;</CodeBlock></div><div className="rounded-xl border border-border bg-card/50 p-5"><div className="mb-4 flex items-center gap-2 text-xs font-semibold"><Activity size={15} className="text-success" /> System status</div><div className="flex items-center justify-between border-b border-border pb-3 text-sm"><span className="text-muted-foreground">All systems operational</span><span className="text-xs text-success">99.9%</span></div><div className="mt-3 flex justify-between text-[11px] text-muted-foreground"><span>Last incident</span><span className="text-foreground">Never</span></div></div></div></main>{toast && <div role="status" className="fixed bottom-5 left-1/2 z-30 flex -translate-x-1/2 items-center gap-2 rounded-lg border border-border bg-card px-4 py-3 text-xs shadow-2xl"><Check size={14} className="text-success" /> {toast}</div>}</div>
}
