export type ApiCategory = "All" | "Downloader" | "Tools" | "Search" | "Media" | "Utility"
export type ApiMethod = "GET" | "POST" | "PUT" | "DELETE"
export type Endpoint = { id: string; name: string; method: ApiMethod; path: string; category: Exclude<ApiCategory, "All">; description: string; params: { name: string; type: string; required: boolean; example: string }[]; example: string }

export const endpoints: Endpoint[] = [
  { id: "instagram", name: "Instagram Downloader", method: "GET", path: "/api/v1/download/instagram", category: "Downloader", description: "Download Instagram reels, posts, and media from a public URL.", params: [{ name: "url", type: "string", required: true, example: "https://instagram.com/reel/..." }], example: '{\n  "status": true,\n  "title": "BMW M4 Competition",\n  "download_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "tiktok", name: "TikTok Downloader", method: "GET", path: "/api/v1/download/tiktok", category: "Downloader", description: "Fetch TikTok video metadata and a clean download URL.", params: [{ name: "url", type: "string", required: true, example: "https://tiktok.com/@user/video/..." }], example: '{\n  "status": true,\n  "author": "@bmw.motorsport",\n  "download_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "youtube", name: "YouTube Downloader", method: "GET", path: "/api/v1/download/youtube", category: "Downloader", description: "Resolve YouTube videos into downloadable media formats.", params: [{ name: "url", type: "string", required: true, example: "https://youtube.com/watch?v=xxxx" }, { name: "format", type: "string", required: false, example: "mp4" }], example: '{\n  "status": true,\n  "title": "BMW M Hybrid V8",\n  "format": "mp4",\n  "download_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "spotify", name: "Spotify Downloader", method: "GET", path: "/api/v1/download/spotify", category: "Media", description: "Get track information and audio from a Spotify URL.", params: [{ name: "url", type: "string", required: true, example: "https://open.spotify.com/track/..." }], example: '{\n  "status": true,\n  "title": "The Ultimate Driving Machine",\n  "artist": "BMW APIs",\n  "download_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "geo", name: "Geo Lookup IP", method: "GET", path: "/api/v1/tools/geo-ip", category: "Tools", description: "Retrieve location, network, and timezone details for an IP address.", params: [{ name: "ip", type: "string", required: true, example: "8.8.8.8" }], example: '{\n  "status": true,\n  "ip": "8.8.8.8",\n  "country": "United States",\n  "city": "Mountain View"\n}' },
  { id: "whatsapp", name: "Lookup WhatsApp", method: "POST", path: "/api/v1/tools/whatsapp", category: "Tools", description: "Check whether a phone number is registered on WhatsApp.", params: [{ name: "phone", type: "string", required: true, example: "+628123456789" }], example: '{\n  "status": true,\n  "registered": true,\n  "international": "+628123456789"\n}' },
  { id: "song", name: "Find Song", method: "GET", path: "/api/v1/search/song", category: "Search", description: "Identify a song from a short audio query or title.", params: [{ name: "query", type: "string", required: true, example: "The Weeknd Blinding Lights" }], example: '{\n  "status": true,\n  "title": "Blinding Lights",\n  "artist": "The Weeknd",\n  "confidence": 0.98\n}' },
  { id: "2fa", name: "2FA Check", method: "GET", path: "/api/v1/utility/2fa", category: "Utility", description: "Validate a two-factor authentication token against a secret.", params: [{ name: "secret", type: "string", required: true, example: "JBSWY3DPEHPK3PXP" }, { name: "code", type: "string", required: true, example: "123456" }], example: '{\n  "status": true,\n  "valid": true,\n  "expires_in": 21\n}' },
]

export const categories: { label: ApiCategory; count?: number }[] = [{ label: "All" }, { label: "Downloader", count: 7 }, { label: "Tools", count: 10 }, { label: "Search" }, { label: "Media" }, { label: "Utility" }]
