export type ApiCategory = "All" | "Downloader" | "Tools" | "Search" | "Media" | "Utility"
export type ApiMethod = "GET" | "POST" | "PUT" | "DELETE"
export type Endpoint = { id: string; name: string; method: ApiMethod; path: string; category: Exclude<ApiCategory, "All">; description: string; params: { name: string; type: string; required: boolean; example: string }[]; example: string }

const urlParam = (example: string) => [{ name: "url", type: "string", required: true, example }]

export const endpoints: Endpoint[] = [
  { id: "tiktok", name: "BMW APIs · TikTok Downloader", method: "GET", path: "/api/v1/bmw_apis/tiktok", category: "Downloader", description: "Get TikTok video, photo, audio, and creator metadata from a public URL.", params: urlParam("https://vt.tiktok.com/ZSxaSfTDq/"), example: '{\n  "Status": true,\n  "Result": {\n    "Type": "video",\n    "Url_video": "https://cdn.bmwapis.dev/...",\n    "Url_audio": "https://cdn.bmwapis.dev/..."\n  }\n}' },
  { id: "youtube", name: "BMW APIs · YouTube Downloader", method: "GET", path: "/api/v1/bmw_apis/youtube", category: "Downloader", description: "Resolve a YouTube URL into a downloadable audio or video file.", params: [{ name: "url", type: "string", required: true, example: "https://youtu.be/gs-F5seOoOk" }, { name: "format", type: "string", required: false, example: "mp4 or mp3" }], example: '{\n  "status": "ready",\n  "input": { "url": "https://youtu.be/...", "format": "mp4" },\n  "result": { "download_url": "https://cdn.bmwapis.dev/..." }\n}' },
  { id: "instagram", name: "BMW APIs · Instagram Downloader", method: "GET", path: "/api/v1/bmw_apis/instagram", category: "Downloader", description: "Get Instagram post, reel, carousel media, thumbnails, and public post metadata.", params: urlParam("https://www.instagram.com/p/DaAFragD2ID/"), example: '{\n  "Status": true,\n  "post_info": {\n    "username": "bmw",\n    "caption": "BMW M4 Competition"\n  },\n  "medias": [{ "download_url": "https://cdn.bmwapis.dev/..." }]\n}' },
  { id: "threads", name: "BMW APIs · Threads Downloader", method: "GET", path: "/api/v1/bmw_apis/threads", category: "Downloader", description: "Extract public Threads video and image media with quality and dimensions.", params: urlParam("https://www.threads.com/@username/post/ABC123"), example: '{\n  "Status": true,\n  "Type": "video",\n  "Total": 1,\n  "Result": [{\n    "Result_url": "https://cdn.bmwapis.dev/..."\n  }]\n}' },
  { id: "y2mate", name: "BMW APIs · Y2Mate Converter", method: "GET", path: "/api/v1/bmw_apis/y2mate", category: "Media", description: "Analyze and convert a YouTube URL with selectable mp3 or mp4 output formats.", params: [{ name: "url", type: "string", required: true, example: "https://youtu.be/nNcWorl87h0" }, { name: "format", type: "string", required: false, example: "mp3" }, { name: "quality", type: "string", required: false, example: "128kbps" }], example: '{\n  "Status": true,\n  "Type": "mp3",\n  "Quality": "128kbps",\n  "Result_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "downr", name: "BMW APIs · Downr Downloader", method: "GET", path: "/api/v1/bmw_apis/downr", category: "Downloader", description: "Download supported public social media URLs through the BMW APIs media resolver.", params: urlParam("https://vt.tiktok.com/ZSxxpjmUV/"), example: '{\n  "Status": true,\n  "Code": 200,\n  "Input": "https://vt.tiktok.com/...",\n  "Result": { "download_url": "https://cdn.bmwapis.dev/..." }\n}' },
  { id: "spotify", name: "BMW APIs · Spotify Downloader", method: "GET", path: "/api/v1/bmw_apis/spotify", category: "Media", description: "Get track information and audio from a Spotify URL.", params: urlParam("https://open.spotify.com/track/..."), example: '{\n  "status": true,\n  "title": "The Ultimate Driving Machine",\n  "download_url": "https://cdn.bmwapis.dev/..."\n}' },
  { id: "geo", name: "BMW APIs · Geo Lookup IP", method: "GET", path: "/api/v1/tools/geo-ip", category: "Tools", description: "Retrieve location, network, and timezone details for an IP address.", params: [{ name: "ip", type: "string", required: true, example: "8.8.8.8" }], example: '{\n  "status": true,\n  "ip": "8.8.8.8",\n  "country": "United States",\n  "city": "Mountain View"\n}' },
  { id: "song", name: "BMW APIs · Find Song", method: "GET", path: "/api/v1/search/song", category: "Search", description: "Identify a song from a short audio query or title.", params: [{ name: "query", type: "string", required: true, example: "The Weeknd Blinding Lights" }], example: '{\n  "status": true,\n  "title": "Blinding Lights",\n  "artist": "The Weeknd",\n  "confidence": 0.98\n}' },
  { id: "2fa", name: "BMW APIs · 2FA Check", method: "GET", path: "/api/v1/utility/2fa", category: "Utility", description: "Validate a two-factor authentication token against a secret.", params: [{ name: "secret", type: "string", required: true, example: "JBSWY3DPEHPK3PXP" }, { name: "code", type: "string", required: true, example: "123456" }], example: '{\n  "status": true,\n  "valid": true,\n  "expires_in": 21\n}' },
]

export const categories: { label: ApiCategory; count?: number }[] = [{ label: "All" }, { label: "Downloader", count: 5 }, { label: "Tools", count: 1 }, { label: "Search" }, { label: "Media", count: 2 }, { label: "Utility" }]
